# Generated by Django 3.1.12 on 2025-08-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_role', models.CharField(max_length=100)),
                ('ad_status', models.CharField(default='0', max_length=100)),
                ('ad_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('de_id', models.IntegerField()),
                ('de_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('co_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('co_name', models.CharField(max_length=100)),
                ('co_mobile', models.CharField(max_length=100)),
                ('co_email', models.CharField(max_length=100)),
                ('co_subject', models.CharField(max_length=100)),
                ('co_message', models.CharField(max_length=100)),
                ('co_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('de_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('de_name', models.CharField(max_length=100)),
                ('de_status', models.CharField(default='0', max_length=100)),
                ('de_image', models.FileField(upload_to='app/static/media/images')),
            ],
        ),
        migrations.CreateModel(
            name='DesignSteps',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ar_de_id', models.CharField(default='', max_length=100)),
                ('ar_name', models.CharField(max_length=100)),
                ('ar_image', models.ImageField(upload_to='app/static/images/')),
                ('ar_description', models.TextField(default='')),
                ('ar_status', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PredictHistory',
            fields=[
                ('ph_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ph_age', models.IntegerField()),
                ('ph_gender', models.CharField(max_length=10)),
                ('ph_height_cm', models.FloatField()),
                ('ph_chest_cm', models.FloatField()),
                ('ph_waist_cm', models.FloatField()),
                ('ph_hips_cm', models.FloatField()),
                ('ph_shoulder_cm', models.FloatField()),
                ('ph_occasion', models.CharField(max_length=50)),
                ('ph_predicted_outfit', models.CharField(max_length=100)),
                ('ph_created_by', models.CharField(blank=True, default='', max_length=100)),
                ('ph_status', models.CharField(default='0', max_length=10)),
                ('ph_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('rg_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('rg_name', models.CharField(max_length=100)),
                ('rg_mobile', models.CharField(max_length=100)),
                ('rg_email', models.CharField(max_length=100)),
                ('rg_password', models.CharField(max_length=100)),
                ('rg_address', models.CharField(default='', max_length=100)),
                ('rg_secret_key', models.CharField(default='', max_length=100)),
                ('rg_status', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
