# Generated by Django 3.1.12 on 2025-08-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='ph_id',
            field=models.IntegerField(default=0),
        ),
    ]
